### ISSUE TITLE
Could not use jfrog rt gradle command during Bintray brownout

### ISSUE THREAD

**Issue by danielpeach** [jfrog/jfrog-cli#1052]
**Describe the bug**
During the [Bintray brownout](https://status.bintray.com/) today, I couldn't use any `jfrog rt gradle ...` commands since those commands are dependent on [jars hosted in jcenter](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-DownloadingtheMavenandGradleExtractorJARs).

**Expected behavior**
Those jars should be hosted somewhere else and this CLI should point to them 😄. 

**Versions**
- JFrog CLI version: 1.45.2

**Comment by eyalbe4** [comment]
@danielpeach,
The latest release of JFrog CLI downloads the build-info extractors from https://oss.jfrog.org/artifactory/oss-release-local/ instead of jcenter.
In addition, if you prefer to proxy this repository from your own Artifactory server, the new release exposes the new [JFROG_CLI_EXTRACTORS_REMOTE](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-EnvironmentVariables) envirobment varieble, which allows you to do this. The old JFROG_CLI_JCENTER_REMOTE_SERVER and JFROG_CLI_JCENTER_REMOTE_REPO environment variables have been deprecated.
