### ISSUE TITLE
unable to upload build using jfrog cli

### ISSUE THREAD

**Issue by manojsoude** [jfrog/jfrog-cli#1082]
Hi,

I'm unable to upload build using jfrog cli, if run command without `interactive=false` getting wrong number, can you please take a look and correct me

env JFROG_CLI_OFFER_CONFIG=false CI=false JFROG_CLI_LOG_LEVEL=DEBUG jfrog rt u test-testing-20210520-112236.tar interactive=false --url=https://artifactory.tests.com/artifactory/test-maven-local/test/testing/20210520-112236/ --user=**** --apikey=****

```
+ env JFROG_CLI_OFFER_CONFIG=false CI=false JFROG_CLI_LOG_LEVEL=DEBUG jfrog rt u test-testing-20210520-112236.tar interactive=false --url=https://artifactory.tests.com/artifactory/test-maven-local/test/testing/20210520-112236/ --user=**** --apikey=****
[Debug] Usage Report: Sending info...
[Debug] Sending HTTP GET request to: https://artifactory.tests.com/artifactory/test-maven-local/test/testing/20210520-112236/api/system/version
[Info] [Thread 2] Uploading artifact: test-testing-20210520-112236.tar
[Debug] Sending HTTP PUT request to: https://artifactory.tests.com/artifactory/test-maven-local/test/testing/20210520-112236/interactive=false/test-testing-20210520-112236.tar
[Debug] Usage Report: Artifactory response: 404 Not Found
{
  "errors": [
    {
      "status": 404,
      "message": "File not found."
    }
  ]
}
[Debug] [Thread 2]  Artifactory response: 201 Created 
[Debug] Uploaded 1 artifacts.
{
  "status": "success",
  "totals": {
    "success": 1,
    "failure": 0
  }
}
```

**Comment by yahavi** [comment]
@manojsoude,
The upload command receives 2 parameters: local source path and remote target path.
In the command you ran, the CLI took the `interactive=false` as a target path in Artifactory. Moreover, there is no `--interactive` flag in upload, since it is not an interactive command. 
The URL in the `--url` flag should contain only the base path to Artifactory. 

To sum it up, try to run the following command instead:
```
JFROG_CLI_OFFER_CONFIG=false CI=false jfrog rt u test-testing-20210520-112236.tar test-maven-local/test/testing/20210520-112236/ --url=https://artifactory.tests.com/artifactory --user=**** --apikey=****
```

For more information, see the relevant documentation here:
https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-UploadingFiles

Please let us know if this information helped.

**Comment by manojsoude** [comment]
@yahavi Thank you it worked as expected , appreciate your quick help.
