### ISSUE TITLE
No download file for 1.51.2 but release notes available

### ISSUE THREAD

**Issue by s-geiger-si** [jfrog/jfrog-cli#1233]
According to the Release nodes version 1.51.2 was released on 31st of August;
https://github.com/jfrog/jfrog-cli/commit/30121d66bc623505f0d8244460975ab016c5d8e4

But, when I go to the link below, then I do not see an artifact for version 1.51.2, the last build seems to be 1.51.1, is that correct?

See: https://releases.jfrog.io/artifactory/jfrog-cli/v1/

When I try to directly download https://releases.jfrog.io/artifactory/jfrog-cli/v1/1.51.2/jfrog-cli-linux-amd64/jfrog then I receive 404, file not found.

Has the tag been forgotten? Or is this not yet released?

**Comment by eyalbe4** [comment]
@s-geiger-si -
Allow me to appologize for the confusion caused by this.
Version 1.51.2 (and also 2.3.1) were released only for the debian and rpm distribution of JFrog CLI. To avoid further confusion, we will refrain from not releasing a patch for all distributions.
Version 1.51.1 is identical to 1.51.2, if you're not using the debian installer.

**Comment by s-geiger-si** [comment]
Understood, thanks a lot for the quick response.
