### ISSUE TITLE
What is the purpose of https://github.com/jfrog/jfrog-cli/pull/1283 ?

### ISSUE THREAD

**Issue by testworksau** [jfrog/jfrog-cli#1346]
In version 2.6.1, a changeset is included titled `Shorten executable name to jf.`

https://github.com/jfrog/jfrog-cli/blob/v2/RELEASE.md#261-november-22-2021

It seems to have come from this PR: https://github.com/jfrog/jfrog-cli/pull/1283

The windows executable is still `jfrog.exe` - I'm wondering what the intention was as the PR has no description.

**Comment by eyalbe4** [comment]
@testworksau,

JFrog CLI now also supports a shorter executable name - ```jf``` in addition to the legacy ```jfrog```. This change was implemented with additional improvements to the commands' syntax, to make it easier to use JFrog CLI. For backward compatibility, we introduced a series of new installers, to install JFrog CLI with the new executable name. The old installers are still available and will not be removed. 
You can see all the installers [here](https://www.jfrog.com/confluence/display/CLI/JFrog+CLI#JFrogCLI-Downloadandinstallation).
Since ```jf``` is more convenient, the main [download page](https://jfrog.com/getcli/) will be soon updated to include the ```jf``` installers and download links only.

Please let us know if you have follow-up questions, comments or suggestions.

**Comment by testworksau** [comment]
Thanks for the clarification @eyalbe4 👍🏼 

We typically either download via curl (`curl -fL https://getcli.jfrog.io | sh`), chocolatey (`choco install jfrog-cli`) or use the docker image (`jfrog/jfrog-cli-v2`)  so provided these installer packages won't suddenly start installing `jf` binaries instead of `jfrog` binaries, we're good (and that's what it sounds like you're saying). 

The chocolatey package started installing the v2 package which caused a little bit of grief as we were using the deprecated configuration commands, but we accepted that responsibility as we had been warned they were deprecated for some time 😄

**Comment by eyalbe4** [comment]
Correct @testworksau.
Our apologies for the Chocolatey incident. Our intent was to release a new jfrog-cli-v2 package, but it emded up overwriting the existing jfrog-cli package. We also created a new jfrog-cli-v2-jf Chocolatey package, but it seems to be still pending in the review queue. Hopefully it'll be approved soon. That's why there isn't a Chocolatey package for ```jf``` in the above documentation link.
