### ISSUE TITLE
Digitally sign binaries (Linux and others)

### ISSUE THREAD

**Issue by jornfranke** [jfrog/jfrog-cli#1355]
**Is your feature request related to a problem? Please describe.**
It is common practice in many open source projects to digitally code sign their binaries to make sure that they have not been tampered with. There is some work on-going to offer this for Windows binaries https://github.com/jfrog/jfrog-cli/issues/34 , but it should be done for all binaries of JFrog Cli - especially Linux binaries.

**Describe the solution you'd like to see**
The Linux binary (possibly all binaries) are signed using [gpg](https://en.wikipedia.org/wiki/GNU_Privacy_Guard) or similar (e.g. [sigstore](https://github.com/sigstore)). The resulting signature (.asc and .sig format) is provided as an additional file. The public keys to verify the signature should be distributed on a different server from the one hosting the signature and additionally on keyservers.

The signing process should be ideally happening as part of the automated build process and private keys should be protected in secure enclaves. As a first step, signing per se is though already a benefit and additional protection of the software supply chain can be introduced later.

**Describe alternatives you've considered**
No alternatives possible. Not signed binaries become more and more an issue.

**Additional context**
-

**Comment by eyalbe4** [comment]
Thank you for raising this request @jornfranke.
Both the Debian and RPM install commands of JFrog CLI have been updated to use JFrog's public GPG key. See the updated commands [here](https://www.jfrog.com/confluence/display/CLI/JFrog+CLI#JFrogCLI-Downloadandinstallation). Soon the [Get JFrog CLI](https://jfrog.com/getcli/) will be updated as well.
Since **Chocolatey** is used on Windows, and the Windows binary is digitally signed using CodeSign, then it appears to be good as well.
We will look further into the other installation methods.
