### ISSUE TITLE
What is the motivation to rename a cli that is used in thousands of scripts ?

### ISSUE THREAD

**Issue by vdsbenoit** [jfrog/jfrog-cli#1594]
Dear jfrog-cli developers,

May I kindly ask you what is the motivation to refactor the name of your CLI ? I guess you know that most of your customers use your CLI for scripting. As far as we are concerned, the term `jfrog` is literally everywhere in our build scripts & other CI-related stuff. Migrating to `jf` would be a nightmare... 

The only communication I found about it is this sentence, on JFrog Confluence documentation: 
> In an effort to make the CLI usage easier and more convenient, we recently exposed a series of new installers, which install JFrog CLI with the new jf executable name

What is more easier and convenient in typing 3 less characters ? Something that is really inconvenient is to break an API and even worse : change the name of the CLI tool. It is not the first time you do so (e.g. `jfrog rt config`, `--apikey`, etc). What is going to be the next one ? `jfrog rt dwnld` instead of `jfrog rt dl` ? We already had to refactor our scripts a couple of times due to features you drop. This is driving developers crazy. They don't want to spend their days refactoring build scripts instead of coding features. I have the feeling you do not evaluate the impact of such removals before applying them. We accepted it the first time but now we start questioning whether we can consider your tool as stable and professional. 

I know you keep on providing the tool under the `jfrog` name but it's getting more an more tricky to get access to it. Every month, I get complains from colleagues who installed the `jf` version because the `jfrog` one is now hidden somewhere in JFrog documentation. 

At least, may I ask you to systematically ask the user to choose between `jfrog` & `jf` on https://jfrog.com/getcli ? The way you push your long running customers to use `jf` is not fair. 

Cheers

**Comment by eyalbe4** [comment]
@vdsbenoit,

1. JFrog CLI includes more and more features and capabilities that can be used by individual developers, and not just by automation scripts. The relatively new "jf docker scan" command is just one example. We therefore wanted to make it easier for everybody to type the commands in the terminal. Try typing "jfrog" multiple times, compared to typing "jf".

2. A major version for JFrog CLI is released only once a few years. Ever since JFrog CLI was launched a few years ago, we released only one major version (v2). Commands that are scheduled to be removed in the next major release prompt a deprecation warning message with the mew usage. This warning message is added a very long time before the next major release is even planned. Also, as I mentioned earlier, there's no rush to move to the mew major release after it is out. You can continue using the old major release for as long as you need to. Upgrading to the new major is recommended however, to enjoy new features amd enhancements.

**Comment by vdsbenoit** [comment]
1. I tend not to agree with you, CLI users who want a shorter command usually create aliases. But, all right, let's say it is a debate topic. I just wonder what is the proportion of users using `jf docker scan` interactively vs the one using it for scripting. I believe it would have been fair to poll your users about such a change before deliberately forcing it. 

2. Even though your answer sounds reassuring for the future, I don't think this strategy was applied in the past. A simple search for "replac" or "breaking change" in [the v1 release notes](https://github.com/jfrog/jfrog-cli/blob/v1/RELEASE.md) can tell. For instance, [this release](https://github.com/jfrog/jfrog-cli/blob/v1/RELEASE.md#1450-march-9-2021) was not a major release AFAIK. It introduced a breaking change though...

**Comment by eyalbe4** [comment]
@vdsbenoit,
There's a chance the below change item could be better phrased, but it did not remove the old `jfrog rt config` command, but merely added the new command. The old command was removed only on JFrog CLI v2.
<img width="748" alt="image" src="https://user-images.githubusercontent.com/7830056/178096205-64e923ee-73ee-479b-944b-7e759c6fbca4.png">

**Comment by vdsbenoit** [comment]
You are right, it displays a warning message about the deprecation and does not fail, my bad. Thank you for your time. I'm closing this issue if that's okay for you.
