### ISSUE TITLE
jf audit and xray command flags purpose ?

### ISSUE THREAD

**Issue by vmiko** [jfrog/jfrog-cli#1612]
Hello,

Before to describe my question, note that I run my commands with the jf cli in 2.21.5 version.

I have a monorepo project with a _package.json_ and a _pom.xml_ in the same directory.
I would like to execute an audit with `jf audit` either on the npm or mvn project so I put the _--npm_ or _--mvn_ flag to the  `jf audit` command.

When I run `jf audit --npm`, the jf cli only audit the npm project as expected.
If I run a `jf audit --mvn` command, its execute an audit for both npm and mvn project. 

Is it the normal behaviour ? If yes, what is the purpose of the xray command flags if we cannot audit one specific project ?

**Comment by sverdlov93** [comment]
Hi @vmiko,
Thanks for reporting this issue.
The '--mvn' flag should run a specific audit as you see on npm and on all other techs.
Our apologies for the inconvenience caused by this bug.
This PR - https://github.com/jfrog/jfrog-cli/pull/1613 should fix it.
I will update this thread once the next release is out.

**Comment by vmiko** [comment]
Hi @sverdlov93 
Thanks a lot for your reactivity and your fix.

I'm waiting for the next release.

**Comment by sverdlov93** [comment]
Hi @vmiko, 
[JFrog CLI 2.22.0](https://github.com/jfrog/jfrog-cli/releases/tag/v2.22.0) is released and should fix the above issue.
Looking forward to your feedback on it.
