### ISSUE TITLE
jfrog scan doesn't work on apple m1

### ISSUE THREAD

**Issue by artemijan** [jfrog/jfrog-cli#1617]
Hello, I'm using apple m1 machine to build docker images locally and scan them to check vulnerabilities with jfrog xray. But unfortunately when I run 
`
jf docker scan my-image:latest --format=json
`
I get each time the same result
`
21:44:38 [🔵Info] JFrog Xray Indexer 3.52.4 is not cached locally. Downloading it now...
21:44:39 [🚨Error] failed while attempting to download Xray indexer: 400 Bad Request received when attempting to download https://artemi4.jfrog.io/xray/api/v1/indexer-resources/download/darwin/arm64. An error occurred while trying to read the body of the response: http: read on closed response body
`
The only way for me is to upload the image and wait it to be scanned by xray on the jfrog server.

I'm not sure if this issue is related to the jfrog-cli, could you help me to address this issue?

**Comment by artemijan** [comment]
I've checked scanning in Docker desktop via Jfrog extension and it works, so need to make it work through jfrog-cli :)

**Comment by omerzi** [comment]
Hello @artemijan, thanks for informing us of this issue. 
The issue originates from the Xray indexer app. This indexer-app is downloaded when you run the 'jf docker scan' command, and it scans your image component tree. 
Currently, the indexer-app does not support the mac M1 architecture (arm64), but it will be supported in Xray version 3.54 very soon. 
In regards to the CLI, I can guess that you use an emulator like Rosetta on your Mac, because before version 2.22.0 (released yesterday), it was not compatible with arm64 architecture without rosetta-like emulators. 
Until version 3.54 is released, here is a workaround for the Xray indexer-app if you have an emulator:
`
1. cd ~/.jfrog/dependencies/xray-indexer 
2. mkdir 3.52.4
3. cd 3.52.4
4. jf xr curl -fl --output indexer-app /api/v1/indexer-resources/download/darwin/amd64
5. chmod 777 indexer-app
`
With this workaround you will be able to use the 'jf docker scan' command until Xray indexer-app will support mac arm64 architecture soon.
I hope it will be helpful. Please let me know if you have any further questions.

**Comment by artemijan** [comment]
Thank you for the answer! I really appreciate it.
