### ISSUE TITLE
jf docker scan on Apple M2

### ISSUE THREAD

**Issue by aquacode** [jfrog/jfrog-cli#1933]
Is there any way to scan Docker images using JFrog Xray if I am using an Apple M2?

I cannot use either the Docker app extension nor the CLI.

We are using JFrog version 7.33.12 and Xray 3.43.1 -- it is doubtful we can upgrade right now.

**Comment by sverdlov93** [comment]
Hi @aquacode,
Upgrading Xray is the way to go here, then you will get an arm64 executable that is compatible with your processor.
Also, a lot of changes and improvements were made on Xray side since the above version, including the docker scan feature.

As a workaround, you can try installing Rosetta2 which should help your Mac deal with the amd64 executable.
Let me know if that helped.

**Comment by aquacode** [comment]
Upgrade worked, thanks.
