### ISSUE TITLE
Be more conscious with version number

### ISSUE THREAD

**Issue by schtefan** [jfrog/jfrog-cli#2028]
I get notification about new releases of jfrog-cli. When there is an update of the minor version number, I usually look into the change log what has changed. Often I then see that there are only bug fixes listed.
Please be more conscious with the version number: when adopting the [semantic versioning scheme,](https://en.wikipedia.org/wiki/Software_versioning#Semantic_versioning), implementing only bug fixes means to only increase the patch version. Increasing the minor version implies to provide improvements or new features with API compatibility to the previous version.
Thanks!

**Comment by yahavi** [comment]
@schtefan
Thank you for using the JFrog CLI.
The JFrog CLI relies on several components, including [jfrog-cli-core](https://github.com/jfrog/jfrog-cli-core), [jfrog-client-go](https://github.com/jfrog/jfrog-client-go), [build-info-go](https://github.com/jfrog/build-info-go), and others.

In order to streamline the release process, we have implemented automated release notes generation. Here is how it works:

1. When a developer adds a new feature to jfrog-cli-core.
2. We release a minor version of jfrog-cli-core.
3. We release a minor version of jfrog-cli, with the new the version of jfrog-cli-core. In this particular scenario, it also introduces a new feature to the jfrog-cli.
4. The release notes generator automatically sends an email with the release notes, but it does not include the changes made to jfrog-cli-core.
5. We manually edit the release notes to include the changes made to jfrog-cli-core.

To ensure that the release email always contains accurate information, we have created a pull request at https://github.com/jfrog/jfrog-cli/pull/2059.
To ensure that the release notes sent by email include the relevant information for all components, a human will be responsible for generating the release notes in the upcoming release.

If you have any further questions, please don't hesitate to ask.
