### ISSUE TITLE
Disable the "Zip Slip Symlink exploit" check when using the --explode flag in the 'jf rt download' command

### ISSUE THREAD

**Issue by derekscp** [jfrog/jfrog-cli#2175]
We have a use case where symlinks are commonly used when deploying archives to Artifactory. When downloading that archive with the --explode flag. 

To reproduce this you can create a symlink inside a folder
ln -s Some_Path_location Symlink-Name
Here is an example of a folder being uploaded to Artifactory as an archive.
$ tree
.
└── testdir
    ├── emptydir
    ├── link-test-tmp4l1d9p6d
    ├── afolder
    │   └── common
    │       └── tmp4l1d330p6d.txt
    └── rpm_verify -> ../../trilead-api.hpi
jf rt u "**" example-repo-local/test.zip --flat="false" --symlinks="True" --archive zip

Then if you attempt to download it you will see the error in the logs.
jf rt download example-repo-local/test.zip --explode --threads 2 --split-count=0 
`[Warn] [Thread 1] (Attempt 1) - Failure occurred while downloading <ART_URL>/artifactory/example-repo-local/test.zip: walking rpm_verify: illegal link path in archive: '../../trilead-api.hpi'. To prevent Zip Slip Symlink exploit, the path can't lead to an entry outside '/Users/derekp/testdir/downloads/'`

This was attempted on JFCLI version 2.46.2.

**Describe the solution you'd like to see**
I would like to be able to disable this check on symlinks and allow the extraction of the archive to continue.
Possibly some sort of flag that we can set to true i.e. --disable-explode-symlink-check=true

**Comment by yahavi** [comment]
@derekp This functionality has been available since version [2.37.0](https://github.com/jfrog/jfrog-cli/releases/tag/v2.37.0) in https://github.com/jfrog/jfrog-cli/pull/1899.

If you want to skip the inspection of archives, you can utilize the --bypass-archive-inspection option like this:
`jf rt dl <source> <target> --explode --bypass-archive-inspection`.
However, I would strongly advise against using this flag in a production environment.

For a complete list of available flags for downloading, you can run `jf rt dl -h`.
