### ISSUE TITLE
[🚨Error] platform URL is mandatory for access token creation

### ISSUE THREAD

**Issue by faisal6621** [jfrog/jfrog-cli#2605]
I am using using the `jf atc` command to create an access token for a different user than the logged in. However, I am getting the error
```
[🚨Error] platform URL is mandatory for access token creation
```
![jf atc command result](https://github.com/user-attachments/assets/41862734-c947-415c-8c1f-44c064e5b54a)

I have checked the config and the URL is correctly set.
![image](https://github.com/user-attachments/assets/6c311777-f37b-4e8a-84ab-0b80ee04a3ca)

What can be done in this case?

**Comment by yahavi** [comment]
@faisal6621

It appears you've used the `--user` flag to provide a username. This flag is intended solely for authentication purposes and does not set the target username for the token. For security reasons, when providing any authentication details by flag in the JFrog CLI (such as username, password, URL, etc.), you must provide all of them together to avoid sending valid credentials to the wrong URL.

To generate a token for the user configured by the `jf c add` command, simply run: 
```sh
jf atc --expiry 0 --description "..."
```

To generate a token for another user, provide the username as an argument instead of a flag: 
```sh
jf atc <username> --expiry 0 --description "..."
```

You can read more about this command here: [Creating Access Tokens](https://docs.jfrog-applications.jfrog.io/jfrog-applications/jfrog-cli/configurations/jfrog-platform-configuration#creating-access-tokens)

Please let me know if this helps.

**Comment by faisal6621** [comment]
@yahavi 
Thanks for the clarification. This was not clear from the CLI help documentation.

**Comment by eyalbe4** [comment]
@faisal6621,
Your perspective can help us improve the documentation. 
If you'd like, you can contribute improvements to the documentation by creating pull requests to github.com/jfrog/documentation
