### ISSUE TITLE
jfrog rt delete --dry-run=true should return exit code 1

### ISSUE THREAD

**Issue by onmomo** [jfrog/jfrog-cli#682]
**Describe the bug**
Running `rt delete` with --dry-run parameters always fails with failure and exit code 1. 
I guess it should work like `rt download --dry-run` that returns exit code 0.

**To Reproduce**
Steps to reproduce the behavior
```
jfrog rt delete --dry-run=true --spec resources/rt_filespecs/find-rcs-spec.json --limit 1 --quiet
```

Returns
```
[Info] Searching artifacts...
[Info] Found 1 artifact.
[Info] [Thread 2] [Dry run] Deleting $PATH
{
  "status": "failure",
  "totals": {
    "success": 0,
    "failure": 1
  }
}
```
Process exits with 1.
```
echo $?
1
```
**Expected behavior**
--dry-run should return exit code 0 and success in order to make real use of it on CI.

**Screenshots**

**Versions**
- JFrog CLI version: 1.35.3
- JFrog CLI operating system: macOS / Ubuntu
- Artifactory Version: latest SaaS

**Comment by felipecrs** [comment]
This is still happening as of now.

```sh-session
$ jfrog --version
jfrog version 1.40.1
```

**Comment by dreyTee** [comment]
Still happens on 
**jfrog version 2.6.1**

**Comment by Manisiri** [comment]
any update on this issue.. still facing same issue

**Comment by SaberStrat** [comment]
I could try to fix this, if the maintainers actually consider this a bug. Did some code diving.

I think that, on the high call-level, this happens because the [call](https://github.com/jfrog/jfrog-cli-core/blob/v2.48.1/artifactory/commands/generic/delete.go#L55) to `dc.DeleteFiles(reader)` calculates the number of artifacts to be deleted and the number of actually deleted ones and, when dry-run is set, returns `0, N_tobedeletedwithoutdryrun>0, nil` (see [here](https://github.com/jfrog/jfrog-cli-core/blob/v2.48.1/artifactory/commands/generic/delete.go#L114)), which is interpreted as `success, failed, err`, i.e., a non-zero fail-count, by the `dc.DeleteFiles(reader)` call. And when this result gets passed along to `jfrog-cli-core`'s `coreutils.GetExitCode(err, success, failed, failNoOp)` function, it interprets that as an error because `failed` is non-zero.

So far I'm seeing these options to make the results of a dry-run deletion not get interpreted as a failure:
1. make this module's `artifactory.printBriefSummaryAndGetError(success, failed, failNoOp, err)` [call](https://github.com/SaberStrat/jfrog-cli/blob/v2/artifactory/cli.go#L1474),  function or the error functions down the line until `jfrog-cli-core`'s `coreutils.GetExitCode(...)` turning the non-zero `failed` into an error code be aware of a dry-run mode.\
However, this might be not the right place, as not all commands using a reader might be supporting a dry-run mode.
1. Make `jfrog-client-go`'s `ContentReader` be aware of dry-run modes, for instance its `Length()` method.\
However, this too might be not the right place, as not all commands using a reader might be supporting a dry-run mode.
1. Looking at `jfrog-cli-core`'s `DeleteCommand`, make `GetPathsToDelete()` build the `ContentReader` with dry-run in mind. Right now, the method is working with an `ArtifactoryServiceManager` object that knows of the flag, but doesn't act on it, I think.\
However, this would weaken the value/representativeness of the dry-run.
1. Looking at `jfrog-cli-core`'s `DeleteCommand`, make `DeleteFiles(reader)` handle dry-run mode as a special case in that method.\
However, this isn't very clean.
1. A rethinking how success and failed numbers are calculated from the deletion methods.

**Comment by SaberStrat** [comment]
Could I get some input on this please from someone from jfrog? Not sure who to ping...@yahavi? Sorry in advance, if you're the wrong one to ping.

**Comment by EyalDelarea** [comment]
Hey @onmomo, 
JFrog CLI `v2.54.0` has been released and this issue should be resolved.
Waiting to hear your feedback!

**Comment by SaberStrat** [comment]
It’s nice that there’s been an official PR to fix this. Thanks.

But not replying to a suggestion from the community to contribute, kind of contradicts the statement from the README that contributions were welcome. But maybe it’s really just PRs that are welcome, not discussions, and it’s "first come first serve."

**Comment by pstorch** [comment]
Just tested, with `v2.54.0`. Our pipeline doesn't fail anymore. Thanks.
