### ISSUE TITLE
Does not fallback to ssh-agent for ssh key authentication

### ISSUE THREAD

**Issue by ryanc16** [jfrog/jfrog-cli#703]
**Describe the bug**
As far as I can tell from the documentation, issue #83 , and as it is stated in the configuration setup when running `jfrog rt c`, if a url with ssh:// is provided, and no ssh key path is provided (left blank) the cli will fallback to the local ssh-agent on the system. In this configuration, I am not seeing that behavior. Instead I receive:
[Error] SSH key not specified

**To Reproduce**
Run `jfrog rt c` or edit the ~/.jfrog/jfrog-cli.conf to add an artifactory entry that contains an ssh url pointing to an instance of hosted artifactory.
Mine looks like this:
```json
{
    "artifactory": [
        {
            "url": "ssh://artifactory.mydomain.com",
            "serverId": "ssh",
            "isDefault": true
        }
    ],
    "Version": "1"
}
```
Attempt to download an artifact:
Run `jfrog rt dl <repo>/<file>`
At this point, I am not prompted for SSH key or passphrase.
The ssh-agent should be running. If I run: `ssh-agent` it produces:
```
SSH_AUTH_SOCK=/tmp/ssh-xxxxxxxxx/agent.4571; export SSH_AUTH_SOCK;
SSH_AGENT_PID=4572; export SSH_AGENT_PID;
echo Agent pid 4572;
```
SSH works elsewhere, like git, with the added ssh-key, and it prompts for passphrase.

**Expected behavior**
When the provided artifactory url uses ssh:// and no sshKeyPath is provided in the config, jfrog cli falls back to the system's running ssh-agent. In this configuration, I should be prompted for the SSH key passphrase.

**Screenshots**
N/A

**Versions**
- JFrog CLI version: 1.35.5
- JFrog CLI operating system: CentOS 7.7
- Artifactory Version: 6.17.1 rev 61701900

**Additional context**
When setting up the config to have a url using https:// and an API key, the above commands work as intended. This leads me to believe the hosted instance of artifactory is reachable and configured correctly.

**Comment by RobiNino** [comment]
Hi @ryanc16 , Thanks for reaching out.
The CLI actually tries to authenticate via ssh-agent first, and then falls back to a SSH key, if one was provided.
The error you are seeing, "[Error] SSH key not specified", is probably the error printed after falling back. 

A bit of additional information could help us provide a solution:
1. Could you please run the command again, after setting the env var "JFROG_CLI_LOG_LEVEL=DEBUG"? The error from ssh-agent should be printed to the DEBUG log since it is not thrown by the CLI.
2. Is the prompt for passphrase you are getting in other tools, prompted by the tools or by the ssh-agent?

Thanks

**Comment by eyalbe4** [comment]
@ryanc16,
I'm closing this for now, but please let us know if you still need assistance with this.
