### ISSUE TITLE
1.37.0 - CLI recursively appends same temp directory when resolving config location

### ISSUE THREAD

**Issue by bambro** [jfrog/jfrog-cli#735]
**Describe the bug**
In JFrog CLI v1.37.0 (working in v1.36.0), the client will recursively append the same temporary directory (i.e. in this case `jfrog.cli.868311966`) to the filepath of the `jfrog-cli.conf` file.

Error message:
```
[Debug] Converting JFrog CLI's config to the latest version...
[Debug] Converting JFrog CLI's config to the latest version...
[Error] stat .jfrog/jfrog.cli.868311966/jfrog.cli.868311966/.../jfrog.cli.868311966/jfrog.cli.868311966/jfrog/builds/.../jfrog-cli.conf: file name too long
```

**To Reproduce**
1. Create a sample docker image
2. Run the following command: `./jfrog rt docker-push <image> <docker-repo>`

**Expected behavior**
Expected the same behaviour as in v1.36.0 where the CLI can resolve the location of the `jfrog-cli.conf` file.

**Screenshots**

**Versions**
- JFrog CLI version: 1.37.0
- JFrog CLI operating system: Alpine Linux
- Artifactory Version: N/A

**Additional context**
N/A

**Comment by eyalbe4** [comment]
Thanks for reporting this issue @bambro.
I couldn't reproduce the issue.
Could it be that your *.jfrog* directory (your JFrog CLI home directory) included symlink to itself at some downstream level? This can explain what the copy created a recursive error.
Please let me know. Thanks.

**Comment by bambro** [comment]
hi @eyalbe4 , thanks for the quick response.
We are setting the following CLI environment variables before performing the action:

```
env.JFROG_CLI_OFFER_CONFIG = 'false'
env.JFROG_CLI_BUILD_NAME   = "application-name"
env.JFROG_CLI_BUILD_NUMBER = "XX"
env.JFROG_CLI_HOME_DIR     = '.jfrog'
env.JFROG_CLI_TEMP_DIR     = '.jfrog'
```

Is this setup likely to cause an issue? We have ran this without problems using versions `<=v1.36.0`.

Thanks

**Comment by eyalbe4** [comment]
@bambro,

There's a chance that since the temp dir location is set to the home dir location, this dir now icludes a symlink to itself, causing the backup to fail. 
I suggest setting the temp dir to a different location, and also removing from the home dir everything except for the config files.
You should keep in the home dir only the following:
1. The *jfrog-cli.conf* file.
2. The *security* dir (if it exists).

The reason why you did not experience this issue with previous versions, is because only version 1.37.0 includes a configuration backup step, before the configuration is automatically upgraded, to be compatible with 1.37.0.

Let me know if this helps.

**Comment by bambro** [comment]
hi @eyalbe4 ,

That was indeed the issue, separating out the temp + home directories worked like a charm! Thanks again for information!
