### ISSUE TITLE
Jfrog version 1.38 requires username if using config for the api call using apikey

### ISSUE THREAD

**Issue by Dineshk77** [jfrog/jfrog-cli#764]
Having issues with the latest jfrog cli where the jfrog config requires username for the api calls using apikey  

**version 1.37**
```
jfrog rt config --interactive=false --url=https://domain_url/artifactory --apikey=****
jfrog rt dl myrepo/1.10.0.35/
 Log path: /Users/dineshk7/.jfrog/logs/jfrog-cli.2020-07-02.17-21-53.98900.log
{
  "status": "success",
  "totals": {
    "success": 1,
    "failure": 0
  }
}
```

**version 1.38**

```
./jfrog.dms rt config --interactive=false --url=https://domain_url/artifactory --apikey=****
./jfrog.dms rt dl myrepo/1.10.0.35
[Error] Artifactory response: 400 Bad Request
{
  "error": "invalid_request",
  "error_description": "username is required"
}
```

However for **version 1.38** 
- if you don't set the config, it passes without username
```
./jfrog.dms rt dl myrepo/1.10.0.35/ --apikey=**** --url=https://domain_url/artifactory

To avoid this message in the future, set the JFROG_CLI_OFFER_CONFIG environment variable to false.
The CLI commands require the Artifactory URL and authentication details
Configuring JFrog CLI with these parameters now will save you having to include them as command options.
You can also configure these parameters later using the 'jfrog rt c' command.
Configure now? (y/n) [n]: n

 Log path: /Users/dineshk7/.jfrog/logs/jfrog-cli.2020-07-02.17-14-46.97021.log

{
  "status": "success",
  "totals": {
    "success": 1,
    "failure": 0
  }
}
```

**Comment by bin3377** [comment]
Hit same issue here for upload
```
$ ./jfrog rt c --url=<url> --interactive=false --apikey=$ARTIFACTORY_APIKEY
$ ./jfrog rt u <local-path> <remote-path> --recursive=false
 [Error] Artifactory response: 400 Bad Request
 {
   "error": "invalid_request",
   "error_description": "username is required"
 }
```

**Comment by eyalbe4** [comment]
@bin3377 and @Dineshk77 - thank you for reporting this issue!

This issue is the unintended result of a security enhancement added in version 1.38.0. In this version, JFrog CLI automatically generated time limited access tokens, and uses them, instead of the configured credentials. These access tokens have a 1 hour expiration and are automatically replaced.

Sending an API key without a username is not recommended, although it is still supported by Artifactory. This option has actually been removed from the interactive mode of the **jfrog rt c** command. This option was still supported in the non interactive mode (as you used it above) for backward compatibility. We truly apologise for this unintended breakage.

You can resolve this issue in one of the following two ways:

1. Add the *--user* option, in addition to the *--apikey* to the *jfrog rt c* command. This is the recommended solution.

2. Add the new *--basic-auth-only* option to the *jfrog rt c* command. This option disables the automatic access tokens generation functionality and allows sending the API key without a username.

Looking forward to your feedback and again out apologies for the innocence caused by this issue.

**Comment by eyalbe4** [comment]
@bin3377 and @Dineshk77 - please let us know if you think this issue can be closed.

**Comment by Dineshk77** [comment]
Sure. we modified to use the --user argument. thanks
