### ISSUE TITLE
Delete Artifacts from the specfic repositry folder 

### ISSUE THREAD

**Issue by cloudengineers** [jfrog/jfrog-cli#814]
Hi All,
Can you please Help me on the below query:
Is there any way we can delete the Artifacts for the past 15 days using Jfrog Cli ? 
Below is my folder structure 
microservices-release-local/xyz/microservices/application/app1/2020.1.0.1
microservices-release-local/xyz/microservices/application/app2/2020.1.0.4
We have a folder name called application, under that folder we have 30 different microservices Artifacts with their own build number, we need to perform the clean-up only for those 30 microservices unused builds under the application folder 

Please Note: by using the below command I am able to delete 1 app at a time 
jfrog rt del microservices-release-local/xyz/microservices/application/app1/2020.1.0.1 –quiet
But I need to perform the clean-up for all 30 apps which is under the application folder, any help much appreciated  
Thank you

**Comment by eyalbe4** [comment]
@cloudengineers,
There are a few ways to achieve this. One way is to use a file spec with AQL as shown in **Example 10** in the [JFrog CLI's file specs documentation]( https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-UsingFileSpecs).
Another way is to use a file spec, wich includes a *pattern* instead of *aql*, and use *sortBy* with *created* value, together *limit* or *offset* (depending on the *sortOrder* you choose) to get you the list of files you wish to delete.

**Comment by cloudengineers** [comment]
Thank you @eyalbe4 for your help
i have used spec file to delete my artifacts
