### ISSUE TITLE
Use environment variable JFROG_CLI_CONFIG_FILE

### ISSUE THREAD

**Issue by carlsmedstad** [jfrog/jfrog-cli#882]
**Is your feature request related to a problem? Please describe.**
Due to us storing Artifactory credentials in GitLab CI variables, a common pattern in our pipelines when using Artifactory is:
```sh
jfrog rt upload \
  --url="$ARTIFACTORY_URL" \
  --user="$ARTIFACTORY_USER" \
  --apikey="$ARTIFACTORY_TOKEN" \
  "my_file.txt"
```
This ends up being a bit repetitive and verbose.

We would like to instead store a `jfrog-cli.conf` file as a _file CI variable_ and to be able to refer to that when invoking `jfrog-cli`. Documentation for  _file CI variables_: https://docs.gitlab.com/ee/ci/variables/#custom-environment-variables-of-type-file

When running a job the runner will a create temporary file in an unknown location which we in the job can refer to with the variable name. Since the asked for environment variable does not exist it's not trivial how we're going to use such a config file.

**Describe the solution you'd like to see**
`jfrog-cli` understanding the environment variable `JFROG_CLI_CONFIG_FILE`, that would take precedence over the config file in `JFROG_CLI_HOME_DIR`, would solve this issue. With a `jfrog-cli.conf` stored in the _file CI variable_ `JFROG_CLI_CONFIG_FILE` it would reduce the example above to:
```
jfrog rt upload "my_file.txt"
```

**Describe alternatives you've considered**
For us to have a `jfrog-cli.conf` as a _file CI variable_ right now we would have to create the directory `.jfrog` and move the file to it in every job.

**Additional context**
N/A.

**Comment by eyalbe4** [comment]
Thanks for sharing this requirement @carlsmedstad.

Please let me know if the following functionality, that is already supported by JFrog CLI, can help resolve this issue:
JFrog CLI supports exporting the configuration of an Artifactory server into a token. This token can then be imported by JFrog CLI, and load back the stored configuration. Here's what you can do:

1. On your local machine, configure the details of an Artifactory instance, using the ```jfrog rt c ```command.
2. Use the ```jfrog rt c export the-server-id``` command to export a token which stores the server configuration.
3. Store this token as a secret variable in gitlab.
4. From within your gitlab script, import this token into JFrog CLI's config using this command - ```jfrog rt c import $the-variable-storing-the-token```

Since I'm not a gitlab user, the syntax of using the variable may not be accurate, but I assume gitlab includes the functionality of using the values of variables when running command.
The [setup-jfrog-cli](https://github.com/marketplace/actions/setup-jfrog-cli) GitHub Action uses the exact same approach. See its documentation as a reference.

Looking forward to your feedback.

**Comment by carlsmedstad** [comment]
I did not know about that feature. Storing the configuration as a token in a single CI variable will clean up our pipelines a lot.

Thanks for the quick reply! Feel free to close this.
