### ISSUE TITLE
cannot add metadata to the folder alone . The recursive attribute has no effect.

### ISSUE THREAD

**Issue by wwjjkk** [jfrog/jfrog-cli#887]
**Describe the bug**
 (jfrog version 1.39.5) 
We cannot add metadata to the folder level alone.--recursive attribute has no effect.All subfiles are added with the metadata.
If I have 1000 files in my directory, 1000 subfiles will be added with metadata

**To Reproduce**
Steps to reproduce the behavior

jfrog rt s test-local/test2/
```
[Info] Searching artifacts...
[Info] Found 3 artifacts.
[
  {
    "path": "test-local/test2/test2.txt",
    "type": "file",
    "size": 110,
    "created": "2020-11-04T19:35:22.927+08:00",
    "modified": "2020-11-04T19:35:15.000+08:00",
    "sha1": "06fbe491d2a3d5f390658ab4021a3062865e26e6",
    "md5": "1b3af0dab98c07fd32eaaa53318af874"
  },
  {
    "path": "test-local/test2/test.txt",
    "type": "file",
    "size": 110,
    "created": "2020-11-04T19:35:51.780+08:00",
    "modified": "2020-11-04T19:35:49.000+08:00",
    "sha1": "06fbe491d2a3d5f390658ab4021a3062865e26e6",
    "md5": "1b3af0dab98c07fd32eaaa53318af874"
  },
  {
    "path": "test-local/test2/test3.txt",
    "type": "file",
    "size": 110,
    "created": "2020-11-04T19:36:11.923+08:00",
    "modified": "2020-11-04T19:36:09.000+08:00",
    "sha1": "06fbe491d2a3d5f390658ab4021a3062865e26e6",
    "md5": "1b3af0dab98c07fd32eaaa53318af874"
  }
]
```
jfrog rt sp test-local/test2/ "a=1" --recursive=false
```
[Info] Setting properties...
[Info] [Thread 2] Setting properties on: test-local/test2/test2.txt
[Info] [Thread 1] Setting properties on: test-local/test2/test3.txt
[Info] [Thread 0] Setting properties on: test-local/test2/test.txt
[Info] Done setting properties.
{
  "status": "success",
  "totals": {
    "success": 3,
    "failure": 0
  }
}
```
jfrog rt s test-local/test2/
```
[Info] Searching artifacts...
[Info] Found 3 artifacts.
[
  {
    "path": "test-local/test2/test2.txt",
    "type": "file",
    "size": 110,
    "created": "2020-11-04T19:35:22.927+08:00",
    "modified": "2020-11-04T19:35:15.000+08:00",
    "sha1": "06fbe491d2a3d5f390658ab4021a3062865e26e6",
    "md5": "1b3af0dab98c07fd32eaaa53318af874",
    "props": {
      "a": [
        "1"
      ]
    }
  },
  {
    "path": "test-local/test2/test.txt",
    "type": "file",
    "size": 110,
    "created": "2020-11-04T19:35:51.780+08:00",
    "modified": "2020-11-04T19:35:49.000+08:00",
    "sha1": "06fbe491d2a3d5f390658ab4021a3062865e26e6",
    "md5": "1b3af0dab98c07fd32eaaa53318af874",
    "props": {
      "a": [
        "1"
      ]
    }
  },
  {
    "path": "test-local/test2/test3.txt",
    "type": "file",
    "size": 110,
    "created": "2020-11-04T19:36:11.923+08:00",
    "modified": "2020-11-04T19:36:09.000+08:00",
    "sha1": "06fbe491d2a3d5f390658ab4021a3062865e26e6",
    "md5": "1b3af0dab98c07fd32eaaa53318af874",
    "props": {
      "a": [
        "1"
      ]
    }
  }
]
```

**Expected behavior**
This will cause us to duplicate too much metadata in the same version.Currently, the production environment metadata has exceeded 200 million
We hope to add metadata to the folder only ， not to all the subfiles

**Comment by talarian1** [comment]
Hi @wwjjkk,
This issue was fixed in 1.40.0 release. Please upgrade to the latest [release](https://github.com/jfrog/jfrog-cli/releases/tag/v1.40.1) and let me know if everything is working as you expected. Please be noticed that in order to add metadata just to the folder you will need to use the --include-dirs flag and also give the folder and not its content as input (without the '/'):
`jfrog rt sp example-test-local/test2 "a=1" --recursive=false --include-dirs=true`

**Comment by wwjjkk** [comment]
> Hi @wwjjkk,
> This issue was fixed in 1.40.0 release. Please upgrade to the latest [release](https://github.com/jfrog/jfrog-cli/releases/tag/v1.40.1) and let me know if everything is working as you expected. Please be noticed that in order to add metadata just to the folder you will need to use the --include-dirs flag and also give the folder and not its content as input (without the '/'):
> `jfrog rt sp example-test-local/test2 "a=1" --recursive=false --include-dirs=true`

Yes, as hoped. Thank you

**Comment by wwjjkk** [comment]
@talarian1 

We found new problems in 1.41.1!
--recursive = "true"     The attribute is invalid

We can't set properties for the specified directory and subfiles at the same time.

`jfrog rt sp example-test-local/test2 "a=1" --recursive=true --include-dirs=true`
The above code only set properties  to example-test-local/test2

`jfrog rt sp example-test-local/test2/ "a=1" --recursive=true --include-dirs=true`
The above code only set properties  to example-test-local/test2 set properties  to all subfiles but not set to example-test-local/test2.

And the new version property Settings are not compatible with the old version

Please repair it as soon as possible!

**Comment by talarian1** [comment]
Hi @wwjjkk, 
I don't think we have a problem here. This behavior is consist with other CLI commands like the following search command:
`jfrog rt s "example-test-local/test2" --recursive=true --include-dirs`
Will return a single result (the directory itself).
Regarding:
> No matter how the parameter is set --recursive=“true” or --recursive=”false”
I found it always set recursive=0 in the request url from debug info log。

You are correct that each set-props command will be sent to Artifactory with recursive=0 flag, but that is because the implementation of the set-props command relays on a search command result that took into account the relevant flags.
If in your example the `test2` directory will include sub-folders the following command will set props on the sub-folder content too:
`jfrog rt sp example-test-local/test2/ "a=1" --recursive=true --include-dirs=true
`

**Comment by wwjjkk** [comment]
I mean we can't set properties for the specified directory and subfiles at the same time.
Now we need two commands to set props:
```
jfrog rt sp example-test-local/test2" a=1" --include-dirs=true
jfrog rt sp example-test-local/test2/" a=1" --recursive=true --include-dirs=true
```
But in 1.3x.x version, we can only use one command to achieve the same effect
```
jfrog rt sp example-test-local/test2" a=1" --recursive=true --include-dirs=true
```
The new version will not compatible with the old version（1.3x.x）.
Upgrading the client requires modifying all the pipeline scripts

**Comment by talarian1** [comment]
@wwjjkk 
I understand, but the described behavior of older versions is an outcome of a bug that cause the undesired behavior that you originally reported.
 If its help you can use a file spec in order to achieve the requested output with a single set-props command: 
`example-file-spec.txt:`

```json
{
    "files": [
     {
        "pattern": "example-test-local/test2"
     },
     {
        "pattern": "example-test-local/test2/"
     }
    ]
}
```

`jfrog rt sp "a=1" --spec example-file-spec.txt --include-dirs`

I can't think on any other modification you should consider after upgrading to the last version.
Please let me know if that works fine for you.

**Comment by wwjjkk** [comment]
@talarian1 
Ok, I found an easier way to modify it
```
{
    "files": [{"pattern": "example-test-local/test2*"}]
}
```

or

`jfrog rt sp example-test-local/test2* "a=1" --recursive=true --include-dirs=true`
