### ISSUE TITLE
Deploy Artifacts from Archive

### ISSUE THREAD

**Issue by sm185495** [jfrog/jfrog-cli#947]
I'm trying to deploy artifacts from the archive using this command: 
`curl -u "username:password" -X PUT https://ncr.jfrog.io/artifactory/snapshots/ /19.2.15.2/MSI.zip `
I'm getting back BadCredentials error 
```
 "errors" : [ {
    "status" : 401,
    "message" : "Bad credentials"
  } ]
```
But I have the right to deploy it through the UI. Do I need some additional privileges or my command just wrong?

**Comment by eyalbe4** [comment]
@sm185495,

Your question doesn't seem to be related to JFrog CLI and we were hoping to reserve this space for issues and questions that are related to this project.

From looking at the response you got, it appears that your credentials are wrong.
You can actually use JFrog CLI to test your credentials:
```
jfrog rt ping --url https://ncr.jfrog.io/artifactory --user username --password pwd
```
Make suer to pass the credentials to the above ping command, because the ping doesn't require credentials, and if you don't pass them, the ping may still be successful without authentication attempt.  
Once the ping is successful, try uploading the file using the ```jfrog rt upload``` command, which accepts the same ```--url```, ```--user``` and ```--password``` options.
